chore: Add Fedora40 to nightly acceptance tests

diff --git a/home/.chezmoiscripts/run_after_110-update-completions.zsh.tmpl b/home/.chezmoiscripts/run_after_110-update-completions.zsh.tmpl
--- a/home/.chezmoiscripts/run_after_110-update-completions.zsh.tmpl
+++ b/home/.chezmoiscripts/run_after_110-update-completions.zsh.tmpl
@@ -9,16 +9,20 @@ PATH_old="${PATH}"
 export PATH="${HOME}/.asdf/bin:${HOME}/.asdf/shims:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:${PATH}"
 
 # 1. Update `chezmoi` ZSH completions
-chezmoi completion zsh --output="$(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/chezmoi/_chezmoi"
+chezmoi completion zsh --output="$(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/chezmoi/_chezmoi" || error "Failed to update chezmoi ZSH completions"
 
 {{- if or (lookPath "flux") }}
 # 2. Update `flux` ZSH completions
-flux completion zsh > $(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/flux/_flux
+flux completion zsh > $(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/flux/_flux || error "Failed to update flux ZSH completions"
+{{- end }}
+
+{{- if or (lookPath "kustomize") }}
 {{- end }}
 
 {{- if or (lookPath "kustomize") }}
 # 3. Update kustomize ZSH completions
-kustomize completion zsh > $(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/kustomize/_kustomize
+kustomize completion zsh > $(chezmoi source-path)/dot_oh-my-zsh-custom/plugins/kustomize/_kustomize || error "Failed to update kustomize ZSH completions"
+
 {{- end }}
 
 export PATH="${PATH_old}"
